name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:

    # -------------------------
    # 1. STAGING LAYER CONFIG
    # -------------------------
    staging:
      +schema: staging
      +materialized: view     # staging tables should be views
      +tags: ['staging']

    # -------------------------
    # 2. INTERMEDIATE LAYER CONFIG
    # -------------------------
    intermediate:
      +schema: intermediate
      +materialized: table
      +tags: ['intermediate']

    # -------------------------
    # 3. MARTS LAYER CONFIG
    # -------------------------
    marts:

      dim:
        +schema: marts
        +materialized: table
        +tags: ['marts', 'dimension']

      fact:
        +schema: marts
        +materialized: table
        +tags: ['marts', 'fact']

      core:
        +schema: marts
        +materialized: table
        +tags: ['marts', 'core']
